name: Build Project

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  PROJECT: changeme
  AUTHOR: hugsy
  REPO: hugsy/changeme
  VERBOSE: "1"
  CMAKE_FLAGS: "-DDEBUG=ON -DBUILD_TOOLKIT=ON"

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "${{ matrix.os }}/${{ matrix.platform }}/${{ matrix.configuration }}"

    strategy:
      fail-fast: false
      matrix:
        os: ['windows-2025', 'ubuntu-latest', 'windows-11-arm']
        platform: ['x64']
        configuration: ['RelWithDebInfo']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true

    - name: Sets Windows specific environment variables
      shell: powershell
      run: |
        echo "NB_CPU=$env:NUMBER_OF_PROCESSORS" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      if: startsWith(matrix.os, 'windows-')

    - name: Sets Linux specific environment variables
      run: |
        echo "NB_CPU=$(grep -c ^processor /proc/cpuinfo)" >> $GITHUB_ENV
      if: startsWith(matrix.os, 'ubuntu-')

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: cpp
      if: startsWith(matrix.os, 'ubuntu-')

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: ${{ matrix.platform }}
      if: startsWith(matrix.os, 'windows-')

    - name: Prepare common environment
      run: |
        mkdir build
        mkdir artifact
        
    - name: Prepare Windows environment
      if: startsWith(matrix.os, 'windows-')
      shell: pwsh
      run: |
        $true

    - name: Prepare Linux environment
      if: startsWith(matrix.os, 'ubuntu-')
      shell: bash
      run: |
        true

    - name: Build library
      run: |
        cmake -S . -B ./build ${{ env.CMAKE_FLAGS }}
        cmake --build ./build --verbose --parallel ${{ env.NB_CPU }} --config ${{ matrix.configuration }} --target tests

    - name: Run tests
      run: |
        cd build/tests
        ctest --parallel=${{ env.NB_CPU }} --extra-verbose --cfg=${{ matrix.configuration }}
        cd ../..

    - name: Perform CodeQL Analysis
      if: startsWith(matrix.os, 'ubuntu-')
      uses: github/codeql-action/analyze@v2

    - name: Prepare artifact
      run: |
        cmake --install ./build --config ${{ matrix.configuration }} --prefix ./artifact --verbose

    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT }}_${{ github.ref }}_${{ matrix.os }}_${{ matrix.platform }}_${{ github.sha }}
        path: artifact/

    # - name: Notify on success
    #   if: ${{ success() }}
    #   env:
    #     COMMIT_URL: "https://github.com/${{ env.REPO }}/commit/${{ env.GITHUB_SHA_SHORT }}"
    #     RUN_URL: "https://github.com/${{ env.REPO }}/actions/runs/${{ github.run_id }}"
    #   uses: sarisia/actions-status-discord@v1
    #   with:
    #     nodetail: true
    #     title: SUCCESS building `${{ env.REPO }}` for `${{ matrix.os }}-${{ matrix.platform }}`/${{ matrix.configuration }}
    #     description: |
    #       [Job #${{ github.run_number }}] The CI build `${{ env.GITHUB_SHA_SHORT }}` initiated by ${{ env.GITHUB_ACTOR }} on ${{ env.GITHUB_REPOSITORY }} succeeded:
    #       ● Commit ${{ env.COMMIT_URL }}
    #       ● Branch `${{ env.GITHUB_REF_SLUG }}`
    #       ● Platform ${{ matrix.os }}-${{ matrix.platform }}
    #       ● Configuration ${{ matrix.configuration }}
    #       ● Run details: ${{ env.RUN_URL }}
    #     color: 0x00ff00
    #     username: ${{ github.actor }} via GithubBot
    #     avatar_url: ${{ github.actor.avatar_url }}

    # - name: Notify on test failure
    #   if: ${{ failure() }}
    #   env:
    #     COMMIT_URL: "https://github.com/${{ env.REPO }}/commit/${{ env.GITHUB_SHA_SHORT }}"
    #     RUN_URL: "https://github.com/${{ env.REPO }}/actions/runs/${{ github.run_id }}"
    #   uses: sarisia/actions-status-discord@v1
    #   with:
    #     nodetail: true
    #     title: FAILED building `${{ env.REPO }}` for `${{ matrix.os }}-${{ matrix.platform }}`/${{ matrix.configuration }}
    #     description: |
    #       [Job #${{ github.run_number }}] The CI build `${{ env.GITHUB_SHA_SHORT }}` initiated by ${{ env.GITHUB_ACTOR }} on ${{ env.GITHUB_REPOSITORY }} failed:
    #       ● Commit ${{ env.COMMIT_URL }}
    #       ● Branch `${{ env.GITHUB_REF_SLUG }}`
    #       ● Platform  ${{ matrix.os }}-${{ matrix.platform }}
    #       ● Configuration ${{ matrix.configuration }}
    #       ● Run details: ${{ env.RUN_URL }}
    #     color: 0xff0000
        username: ${{ github.actor }} via GithubBot
        avatar_url: ${{ github.actor.avatar_url }}
